### ISSUE TITLE
Multiple non-frameshifting indels (MNPs) being called "synonymous indel"

### ISSUE THREAD

**Issue by bpow** [jdr0887/binning#12]
locvar 546749775 is listed as NP_001116105.1:p.Asn349delinsAsn but should be p.Thr350Ala

locvar 546967178 is listed as NP_001264044.1:p.Val33delinsVal but should be p.Glu34Leu

**Comment by jdr0887** [comment]
I wrote a test case for both of these and am getting the right aa_start & aa_end, however the protein hgvs expression is off.  Here's what I am getting respectively:

NP_001116105.1:p.Thr350Ser
NP_001264044.1:p.Glu34Val

Could you to double check your expressions?

**Comment by bpow** [comment]
546749775 maps to NM_001122633.2:c.1048_1050delinsGCT. According to [mutalyzer](http://mutalyzer.nl), this corresponds to NM_001122633.2(CPS1_i001):p.(Thr350Ala).

546967178 maps to NM_001277115.1:c.100_101delinsTT. This corresponds to NM_001277115.1(DNAH11_i001):p.(Glu34Leu).

You could also double-check by looking at the sequence:
* For 546749775, this changes an ACC codon to GCT. This codon GCT encodes Ala. Maybe your code is looking up to codon TCG (the reverse) that encodes Ser?
* For 546967178, this changes a GAG codon to a TTG codon, which indeed encodes Leu. GTT, on the other hand, encodes the Val you list.

So yep, I'm pretty sure that the expressions I list are correct.

**Comment by jdr0887** [comment]
Both test cases now pass, how I was splitting the dna sequence to parts was off by 1.
