### ISSUE TITLE
locvar 553562444 should be missense

### ISSUE THREAD

**Issue by bpow** [jdr0887/binning#16]
553562444 (NC_000012.12:g.40484948C>T) should be p.(Ala3999Val)
with transcript position NM_173600.2:g.12050C>T, but binning code calculates the transcript position as 12052 since it is calculating from the contig end rather than the contig start-- and the refseq alignment happens to have an indel that probably needs to be parsed from the CIGAR string in their alignment file.

If you calculate the transcript position anchoring off of the contig start, you get 12050 like it should be, but that's not a generalized solution to the problem that sometimes `transcr_end - transcr_start != contig_end - contig_start` with the refseq.transcr_maps_exons table.

**Comment by bpow** [comment]
The relevant line in `GCF_000001405.33_knownrefseq_alignments.gff3` (probably not the same version as currently loaded in CANVAS, but hopefully this line is similar) is:

```
NC_000012.12	RefSeq	cDNA_match	40479053	40491305	12249.6	+	.	ID=6c7e2d13-f0f1-4759-8269-2074a93cbb3f;Target=NM_173600.2 6155 18409 +;gap_count=1;identity=0.976185;idty=0.999837;num_ident=24717;num_mismatch=11;pct_coverage=97.6619;pct_identity_gap=99.9474;pct_identity_ungap=99.9555;Gap=M6352 I2 M5901
```

The "Gap" attribute is what needs to be taken into account.

**Comment by jdr0887** [comment]
just an update....I have fixed/committed the transcriptPosition problem, but that variant still comes back as nonsense.

**Comment by jdr0887** [comment]
this variant now comes back as having missense variant effect
