### ISSUE TITLE
mis-annotation in 5'UTR

### ISSUE THREAD

**Issue by bpow** [jdr0887/binning#17]
locvar 546704464 (NC_000002.12:g.26477955_26477956delGG) is called as a frameshifting indel in NM_194322.2, specifically NM_194322.2:c.87_88delCC, but this variant occurs before the start codon of that CDS. It should be a 'UTR-5' variant.

The correct c. nomenclature would be NM_194322.2:c.-60_-59delGG

**Comment by jdr0887** [comment]
I just added a test case for this locvar that passes.
