### ISSUE TITLE
regression: 556491808 classified as exonic in NM_145112.2

### ISSUE THREAD

**Issue by bpow** [jdr0887/binning#20]
As of diagnostic_result_version 79, 556491808 (NC_000014.9:g.65076384C>T) is being classified as exonic in NM_145112.2 (with hgvscds of NM_145112.2:c.280G>A).

The variant occurs after the stop codon of NC_145112.2, and the correct HGVS nomenclature should be NM_145112.2:c.*92G>A.

**Comment by bpow** [comment]
Another test case:
loc_var 562030574 (NC_000019.10:g.55014228T>C) is notated as exonic in NM_001256017.2, but the appropriate hgvscds is NM_001256017.2:c.*693A>G

**Comment by bpow** [comment]
loc_var 571354208 should be NM_020166.4:c.-100G>C but is currently listed as NM_020166.4:c.2325+41G>C

**Comment by jdr0887** [comment]
regarding 556491808, I am getting this currently: NM_145112.2:c.661+92G>A.  Is this acceptable?

**Comment by jdr0887** [comment]
And for 562030574, I am getting the following: NM_001256017.2:c.994+693A>G

**Comment by jdr0887** [comment]
And for 571354208, I am now getting the following: NM_020166.4:c.148-100G>C
