### ISSUE TITLE
End coordinates for intronic deletions

### ISSUE THREAD

**Issue by bpow** [jdr0887/binning#22]
522364463 is rendered in HGVS as NM_015627.2:c.531+137_532delGA, but should be c.532+137_532+138del (rather than increment the exonic "anchor" of 532 to get the end position, need to increment the offset into the intron).

This is not a showstopper, since the variant classification (intronic) is still correct.

**Comment by jdr0887** [comment]
Just fixed this in the toHGVS routine.
