### ISSUE TITLE
locvar 569046823 should be in UTR

### ISSUE THREAD

**Issue by bpow** [jdr0887/binning#26]
locvarid 569046823
genomic hgvs NC_000002.12:g.26728581G>A
currently has NM_002246.2:c.915G>A (as a missense variant)
but is located after the stop codon:
[c.*13G>A](http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/allele?hgvs=NC_000002.12:g.26728581G%3EA)

**Comment by bpow** [comment]
Similar:
- locvarid 559726800
- genomic hgvs NC_000017.11:g.44902821G>A
- has NM_213607.2:c.457G>A
- should be [c.*4G>A](http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/allele?hgvs=NC_000017.11:g.44902821G%3EA)

**Comment by bpow** [comment]
other locvars affected:
- 574881802
- 574881810
- 583355625
- 559726800

**Comment by bpow** [comment]
Among the others, this is important because it gets marked as a nonsense but is after stop codon:
- locvarid 575289850
- hgvsgenomic NC_000004.12:g.87663355G>A
- has NM_001079911.2:c.1394G>A
- should be c.*35G>A

**Comment by bpow** [comment]
Another possibly related, but may be in different code path because it involves an indel:
- locvar: 522383386
- given as NM_001099693.1:c.278_279insG
- should be c.*146insG (or c.*146dup)

**Comment by jdr0887** [comment]
For LocatedVariant(522383386), I am getting 'NM_001099693.1:c.366_367insG' for the cds hgvs.  Is this acceptable?  I think this is equivalent to c.*146dup.

**Comment by bpow** [comment]
representing as insG rather than dup is fine, but location is after stop codon and should be noted as such.
