### ISSUE TITLE
Problems with loc_var_id 492040380

### ISSUE THREAD

**Issue by bpow** [jdr0887/binning#8]
This loc_var has a couple of issues:
* There is an ArrayOutOfBounds exception thrown when processing against transcript NM_001167617.1 -- it should be a boundary-crossing deletion against this transcript, but follows the code path for exonic variants.
* For transcripts where it is exonic (like against NM_000249.3), it is being given the protein HGVS expression p.Gly98_Glu102delinsGlu (original_aa 'GFRGE', final_aa 'E') but it doesn't make sense to have deletion and addition of Glu-- should just be p.Gly98_Gly101del (original_aa 'GFRG' and final_aa '' (empty string))

I've created a pull request (#7) that includes the failing test (but not the fix...)

**Comment by bpow** [comment]
Actually, nevermind about the ArrayOutOfBounds part, that was an issue you had already addressed... the HGVS expression part still stands, though.

**Comment by jdr0887** [comment]
The db has records that don't match what the code is producing.  I attached two files, one is a query by LocatedVariant and 'NP_%' protein hgvs.  The second is a toString on the Variants_80_4 instances.  Note that the final_aa is G & not E.  My java code didn't start adding 38 variants up until around loc_var_id of 520 million, so I am going to assume that this came from the python code.  In fact, looking at the Variants_61_2 version of this loc_var_id has the same markup.  Is what I am producing right?  How does this change this issue?

[zxcv.txt](https://github.com/jdr0887/binning/files/1457674/zxcv.txt)
[asdf.txt](https://github.com/jdr0887/binning/files/1457675/asdf.txt)

**Comment by bpow** [comment]
There is quite possibly an error in the older code, but I'm not sure that the new code fixes it:

To clarify: the current code provides an HGVS expression of `NP_000240.1:p.Gly98_Glu102delinsGly` but the older code (taken from CANVAS) gives an HGVS expression of `NP_000240.1:p.Gly98_Glu102delinsGlu` (different inserted variant at the end).

A diagram of the variant itself:

```
Reference:
Nucleotides:  TAT|GGC|TTT|CGA|GGT|GAG
Translation:   Y | G | F | R | G | E

Variant:
Nucleotides:  TAT|G--|---|---|---|-AG
So that corresponds to:
Nucleotides:  TAT|GAG
Which translates to YE
```

So the effect of the variant is that the protein sequence changes from `...YGFRGE...` to `...YE...`. This means the HGVS expression should be `NP_000240.1:p.Gly98_Gly101del`

The older code at least represents the right variant (although the expression is redundant in that it deletes the last Glu but inserts it back. The expression generated by the current code would actually result in `...YG...`

I hope that's clearer, because it took a while to write.

**Comment by jdr0887** [comment]
I have fixed this for 38.  When I applied the same changed to the 37 VariantsFactory, the test cases broke.  I will assume that 37 should stay the way it was & we are only applying this change to the 38 VariantFactory.
